"""
serve_https.py
---------------
Serves this folder (the Price Checker PWA) over HTTPS on the LAN, using
cert.pem/key.pem generated by make_cert.py (in the pricetag_tool folder --
copy those two files into this folder first).

HTTPS is required here because phone browsers only allow camera access
(used for both barcode scanning and QR pairing) on a secure context.

Usage:
    python serve_https.py            # serves on port 8080
    python serve_https.py 8443       # or a custom port

Then on staff phones, visit:
    https://<this-computer's-LAN-IP>:8080

First visit will show a certificate warning (it's self-signed) -- tap
Advanced -> Proceed. See HTTPS-SETUP.md for how to avoid that warning by
installing the cert as trusted on each phone.
"""
import http.server
import os
import socket
import ssl
import sys

PORT = int(sys.argv[1]) if len(sys.argv) > 1 else 8080
HERE = os.path.dirname(os.path.abspath(__file__))
CERT = os.path.join(HERE, "cert.pem")
KEY = os.path.join(HERE, "key.pem")


def _is_private_ipv4(ip):
    if not ip or ip.startswith("127.") or ip.startswith("169.254."):
        return False
    parts = ip.split(".")
    if len(parts) != 4 or not all(p.isdigit() for p in parts):
        return False
    a, b = int(parts[0]), int(parts[1])
    return a == 10 or (a == 172 and 16 <= b <= 31) or (a == 192 and b == 168)


def list_lan_ips():
    """Every private IPv4 address this machine currently has (best guess
    first). A machine with a VPN, Docker Desktop, or a virtual network
    adapter installed can have several -- and the one a phone can actually
    reach isn't always the first guess -- so we list all of them rather than
    picking just one. See pricetag_tool/netinfo.py for the same logic used
    on the flag-server side (duplicated here so this stays a standalone,
    single-file script)."""
    candidates = []
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        s.connect(("8.8.8.8", 80))
        guess = s.getsockname()[0]
        if _is_private_ipv4(guess):
            candidates.append(guess)
    except Exception:
        pass
    finally:
        s.close()
    try:
        _, _, addrs = socket.gethostbyname_ex(socket.gethostname())
        for ip in addrs:
            if _is_private_ipv4(ip) and ip not in candidates:
                candidates.append(ip)
    except Exception:
        pass
    return candidates or ["127.0.0.1"]


def main():
    if not (os.path.exists(CERT) and os.path.exists(KEY)):
        print("cert.pem / key.pem not found in this folder.")
        print("Run make_cert.py in the pricetag_tool folder, then copy")
        print("cert.pem and key.pem into this price-checker-pwa folder.")
        sys.exit(1)

    os.chdir(HERE)
    handler = http.server.SimpleHTTPRequestHandler
    httpd = http.server.ThreadingHTTPServer(("0.0.0.0", PORT), handler)

    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.load_cert_chain(certfile=CERT, keyfile=KEY)
    httpd.socket = ctx.wrap_socket(httpd.socket, server_side=True)

    ips = list_lan_ips()
    print(f"Serving Price Checker PWA over HTTPS")
    print(f"  On this computer:  https://localhost:{PORT}")
    print(f"  On staff phones:   https://{ips[0]}:{PORT}")
    if len(ips) > 1:
        print(f"  If that doesn't load on the phone, also try:")
        for ip in ips[1:]:
            print(f"                     https://{ip}:{PORT}")
        print(
            "  (This machine has more than one network address -- common with a"
            " VPN, Docker Desktop, or virtual adapter installed.)"
        )
    print(
        "  Phone can't connect at all? It's usually Windows Firewall -- run"
        " diagnose_network.py in the pricetag_tool folder."
    )
    print("Press Ctrl+C to stop.")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nStopped.")


if __name__ == "__main__":
    main()
